config/routes.rb
Rails.application.routes.draw do
  #get 'home/zipcode'
  root 'home#index'

  post "zipcode" => 'home#zipcode'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    require 'net/http'
    require 'json'

    @url = "http://www.airnowapi.org/aq/observation/zipCode/current/?format=application/json&zipCode=20002&distance=0&API_KEY=EBB3CF3E-148E-4BD0-AC82-EEE04E360BE0"
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @output = JSON.parse(@response)

    if @output.empty?
        @final_output = "Error"
    elsif !@output
       @final_output = "Error"
    else @output
      @final_output = @output[0]['AQI']
    end

    if @final_output == "Error"
      @api_color = "silver"
    elsif @final_output <= 50
      @api_color = "green"
      @api_descripition = "Good"
    elsif @final_output >= 51 && @final_output <= 100
      @api_color = "yellow"
      @api_descripition = "Acceptable"
    elsif @final_output <= 101 && @final_output <= 150
      @api_color = "orange"
      @api_descripition = "Moderate"
    elsif @final_output <= 151 && @final_output <= 200
      @api_color = "red"
      @api_descripition = "Unhealthy for Sensitive Groups"
    elsif @final_output <= 201 && @final_output <= 300
      @api_color = "purple"
      @api_descripition = "Unhealthy"
    elsif @final_output <= 301
      @api_color = "maroon"
      @api_descripition = "Very Unhealthy"
    end

    def zipcode
      @zip_query = params[:zipcode] 
      if params[:zipcode] == ""
        @zip_query = "zipcode missing"
      else
        @url = "http://www.airnowapi.org/aq/observation/zipCode/current/?format=application/json&zipCode=" + @zip_query.to_s + "&distance=0&API_KEY=EBB3CF3E-148E-4BD0-AC82-EEE04E360BE0"
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @output = JSON.parse(@response)

    if @output.empty?
        @final_output = "Error"
    elsif !@output
       @final_output = "Error"
    else @output
      @final_output = @output[0]['AQI']
    end

    if @final_output == "Error"
      @api_color = "silver"
    elsif @final_output <= 50
      @api_color = "green"
      @api_descripition = "Good"
    elsif @final_output >= 51 && @final_output <= 100
      @api_color = "yellow"
      @api_descripition = "Acceptable"
    elsif @final_output <= 101 && @final_output <= 150
      @api_color = "orange"
      @api_descripition = "Moderate"
    elsif @final_output <= 151 && @final_output <= 200
      @api_color = "red"
      @api_descripition = "Unhealthy for Sensitive Groups"
    elsif @final_output <= 201 && @final_output <= 300
      @api_color = "purple"
      @api_descripition = "Unhealthy"
    elsif @final_output <= 301
      @api_color = "maroon"
      @api_descripition = "Very Unhealthy"
    end

      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Ozone</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
  <%= form_tag zipcode_path, :method => 'POST' do %>
  <%= text_field_tag 'zipcode', nil, placeholder: "Search Zipcode", class: "form-control mr-sm-2"%>  
  <%= submit_tag 'Search', class: "btn btn-outline-primary my-2 my-sm-0"  %>
      
    <% end %>
  
  </div>
</nav>

app/views/home/index.html.erb
<div class="jumbotron <%= @api_color %>">
  <h1 class="display-4"><%= @final_output %></h1>
  <p class="lead">This is the current ozone air quality readout around your neighborhood.</p>
  <hr class="my-4">
  <p><%= @api_descripition %><p>
  <p>Hit "Reload" to update the reading.</p>
  <a class="btn btn-success btn-lg" href="#" role="button">Learn more</a>
</div>

<br/>

app/views/home/zipcode.html.erb
<div class="jumbotron <%= @api_color %>">
  <h1 class="display-4"><%= @final_output %></h1>
  <p class="lead">This is the current ozone air quality readout around your neighborhood.</p>
  <hr class="my-4">
  <p><%= @api_descripition %><p>
  <p>Hit "Reload" to update the reading.</p>
  <a class="btn btn-success btn-lg" href="#" role="button">Learn more</a>
</div>

<br/>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ozone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'home/navbar'%>
  <div class="container">
  <br/>
    <%= yield %>
  </div>
  </body>
</html>